### ISSUE TITLE
Not available in a signed state

### ISSUE THREAD

**Issue by solidfox** [PatrickTulskie/hocus_focus#1]
You should really make this available in the safari extension gallery or something. It's super useful but quite a hassle to install for someone not in the Dev Program.

**Comment by PatrickTulskie** [comment]
Funny. I thought I was the only person using this. I have a dev program key that I use to pass the extension around to people who are curious about it.  I'll look into getting it into the Safari Extension Gallery.

**Comment by solidfox** [comment]
Or put it on your website or something. Looking around the web there are quite a few ppl annoyed by the flaw and no clear easy solution.

You might want to support a few localities though. I had to change your regexp to match google.se to make it work for me in Sweden even tho my system is in English.

Patrick Tulskie notifications@github.com さんからのメール（2015年1月15日木曜日、4:37）:

Funny. I thought I was the only person using this. I have a dev program key that I use to pass the extension around to people.  I'll look into getting it into the Safari Extension Gallery.

**Comment by PatrickTulskie** [comment]
Hey @solidfox instead of dealing with Apple approvals and coming up with an icon and stuff to get it into the gallery I decided to just use github releases.  When I have new releases ready going forward I'll just publish a signed binary for download.  I also updated the README with a link to grab different versions.

I'm open to supporting various localities but I want to make sure however I do that, it remains performant.  Google has like 30+ TLDs so I'm not sure if doing a scan of those is the best way to do it.  I'm going to move that to another issue though.
